td/publishing/urls.py
from django.conf.urls import url
from django.views.generic import TemplateView


from .views import (
    ajax_language_version,
    api_contact,
    ContactList,
    ContactCreate,
    ContactDetail,
    ContactUpdate,
    languages_autocomplete,
    OfficialResourceListView,
    OfficialResourceCreateView,
    OfficialResourceUpdateView,
    OfficialResourceDetailView,
    # PublishRequestCreateView,
    PublishRequestUpdateView,
    PublishRequestDeleteView,
    source_languages_autocomplete,
    resource_language_json,
    resource_catalog_json,
    PublishRequestResubmitView,
    redirect_new_publishing,
)


urlpatterns = [
    url(r"^$", TemplateView.as_view(template_name="publishing/homepage.html"), name="publishing_home"),
    url(r"^api/contacts/", api_contact, name="api_contacts"),
    url(r"^contacts/$", ContactList.as_view(), name="contact_list"),
    url(r"^contacts/create/$", ContactCreate.as_view(), name="contact_create"),
    url(r"^contacts/(?P<pk>\d+)/$", ContactDetail.as_view(), name="contact_detail"),
    url(r"^contacts/(?P<pk>\d+)/update/$", ContactUpdate.as_view(), name="contact_update"),
    url(r"^oresource/$", OfficialResourceListView.as_view(), name="oresource_list"),
    url(r"^oresource/create/$", OfficialResourceCreateView.as_view(), name="oresource_create"),
    url(r"^oresource/(?P<pk>\d+)/$", OfficialResourceDetailView.as_view(), name="oresource_detail"),
    url(r"^oresource/(?P<pk>\d+)/update$", OfficialResourceUpdateView.as_view(), name="oresource_update"),
    # url(r"^publish/request/$", PublishRequestCreateView.as_view(), name="publish_request"),
    url(r"^publish/request/$", redirect_new_publishing, name="publish_request"),
    url(r"^publish/request/(?P<pk>\d+)/", PublishRequestUpdateView.as_view(), name="publish_request_update"),
    url(r"^publish/request/(?P<permalink>\w+)/", PublishRequestResubmitView.as_view(), name="publish_request_resubmit"),
    url(r"^publish/request-reject/(?P<pk>\d+)/", PublishRequestDeleteView.as_view(), name="publish_request_delete"),
    url(r"^ac/langnames/", languages_autocomplete, name="names_autocomplete"),
    url(r"^ac/src-langnames/", source_languages_autocomplete, name="source_names_autocomplete"),
    url(r"^ajax/langversion/", ajax_language_version, name="ajax_language_version"),
    url(r"^catalog.json$", resource_catalog_json, name="resource_catalog_json"),
    url(r"^(?P<kind>\w+)-catalog.json$", resource_catalog_json, name="resource_catalog_json"),
    url(r"^(?P<kind>\w+)-(?P<lang>\w+).json$", resource_language_json, name="resource_language_json"),
]

td/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin

from .views import (
    HomeView,
    AdditionalLanguageListView,
    EthnologueCountryCodeListView,
    EthnologueLanguageCodeListView,
    EthnologueLanguageIndexListView,
    SIL_ISO_639_3ListView,
    WikipediaISOLanguageListView,
    IMBPeopleGroupListView,
    AjaxAdditionalLanguageListView,
    AjaxEthnologueCountryCodeListView,
    AjaxEthnologueLanguageCodeListView,
    AjaxEthnologueLanguageIndexListView,
    AjaxSIL_ISO_639_3ListView,
    AjaxWikipediaISOLanguageListView,
    AjaxIMBPeopleGroupListView,
    codes_text_export,
    names_text_export,
    names_json_export,
    names_json_export_short,
    export_svg,
    languages_autocomplete,
    gateway_languages_autocomplete,
)

urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^siteadmin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^invites/", include("pinax.invitations.urls")),

    url(r"^exports/codes-d43.txt$", codes_text_export, name="codes_text_export"),
    url(r"^exports/langnames.txt$", names_text_export, name="names_text_export"),
    url(r"^exports/langnames.json$", names_json_export, name="names_json_export"),
    url(r"^exports/langnames_short.json$", names_json_export_short, name="names_json_export_short"),
    url(r"^exports/gatewaylanguages-map/$", export_svg, name="gateway_languages_map_export"),

    url(r"^uw/", include("td.resources.urls")),
    url(r"^uw/", include("td.urls_languages")),

    url(r"^publishing/", include("td.publishing.urls")),
    url(r"^api/", include("td.urls_api")),
    url(r"^api/", include("td.api.urls", namespace="api")),
    url(r"^comment/", include("td.commenting.urls", namespace="comment")),
    url(r"^comments/", include("django_comments.urls")),

    url(r"^data-sources/additional-languages/$", AdditionalLanguageListView.as_view(), name="ds_additional_languages"),
    url(r"^data-sources/ethnologue/country-codes/$", EthnologueCountryCodeListView.as_view(), name="ds_ethnologue_country_codes"),
    url(r"^data-sources/ethnologue/language-codes/$", EthnologueLanguageCodeListView.as_view(), name="ds_ethnologue_language_codes"),
    url(r"^data-sources/ethnologue/language-index/$", EthnologueLanguageIndexListView.as_view(), name="ds_ethnologue_language_index"),
    url(r"^data-sources/sil-iso-639-3/$", SIL_ISO_639_3ListView.as_view(), name="ds_sil"),
    url(r"^data-sources/wikipedia/$", WikipediaISOLanguageListView.as_view(), name="ds_wikipedia"),
    url(r"^data-sources/imb/peoplegroups/$", IMBPeopleGroupListView.as_view(), name="ds_imb_peoplegroups"),

    url(r"^ajax/data-sources/additional-languages/$", AjaxAdditionalLanguageListView.as_view(), name="ajax_ds_additional_languages"),
    url(r"^ajax/data-sources/ethnologue/country-codes/$", AjaxEthnologueCountryCodeListView.as_view(), name="ajax_ds_ethnologue_country_codes"),
    url(r"^ajax/data-sources/ethnologue/language-codes/$", AjaxEthnologueLanguageCodeListView.as_view(), name="ajax_ds_ethnologue_language_codes"),
    url(r"^ajax/data-sources/ethnologue/language-index/$", AjaxEthnologueLanguageIndexListView.as_view(), name="ajax_ds_ethnologue_language_index"),
    url(r"^ajax/data-sources/sil-iso-639-3/$", AjaxSIL_ISO_639_3ListView.as_view(), name="ajax_ds_sil"),
    url(r"^ajax/data-sources/wikipedia/$", AjaxWikipediaISOLanguageListView.as_view(), name="ajax_ds_wikipedia"),
    url(r"^ajax/data-sources/imb/peoplegroups/$", AjaxIMBPeopleGroupListView.as_view(), name="ajax_ds_imb_peoplegroups"),

    url(r"^ac/langnames/", languages_autocomplete, name="names_autocomplete"),
    url(r"^ac/gateway-langnames/", gateway_languages_autocomplete, name="gateway_languages")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

td/publishing/models.py
import base64
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from jsonfield import JSONField
from reversion import revisions as reversion

from td.models import Language
from td.publishing.resources import RESOURCE_TYPES


class Organization(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of Organization")
    email = models.CharField(max_length=255, blank=True, verbose_name="Email address")
    phone = models.CharField(max_length=255, blank=True, verbose_name="Phone number")
    website = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    languages = models.ManyToManyField(Language, related_name="organizations")
    other = models.TextField(blank=True, verbose_name="Other information")
    checking_entity = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of contact")
    email = models.CharField(max_length=255, blank=True, verbose_name="Email address")
    d43username = models.CharField(max_length=255, blank=True, verbose_name="Door43 username")
    location = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=255, blank=True, verbose_name="Phone number")
    languages = models.ManyToManyField(Language, related_name="contacts")
    org = models.ManyToManyField(Organization, blank=True, verbose_name="organizations")
    other = models.TextField(blank=True, verbose_name="Other information")

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class ConnectionType(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of Connection Type")
    mutual = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class Connection(models.Model):
    con_src = models.ForeignKey(Contact, related_name="source_connections")
    con_dst = models.ForeignKey(Contact, related_name="destination_connections", verbose_name="Connection")
    con_type = models.ForeignKey(ConnectionType, verbose_name="Type")

    class Meta:
        ordering = ["con_src"]

    def __unicode__(self):
        return self.con_src.name


class RecentCommunication(models.Model):
    contact = models.ForeignKey(Contact, related_name="recent_communications")
    communication = models.TextField(blank=True, verbose_name="Message")
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        ordering = ["contact", "created"]

    def __unicode__(self):
        return self.contact.name


CHECKING_LEVEL_CHOICES = [
    (1, "1"),
    (2, "2"),
    (3, "3"),
]


@python_2_unicode_compatible
class OfficialResourceType(models.Model):
    short_name = models.CharField(max_length=5, help_text="a 5 character identification code")
    long_name = models.CharField(max_length=50, help_text="a more descriptive name")
    description = models.TextField(blank=True)

    def ingest(self, language, publish_request):
        ResourceIngestor = RESOURCE_TYPES.get(self.short_name)
        if ResourceIngestor:
            resource_ingestor = ResourceIngestor(language.code, publish_request)
            chapters = resource_ingestor.fetch_chapters()
            resource_doc = ResourceDocument()
            resource_doc.json_data = chapters
            resource_doc.publish_request = publish_request
            resource_doc.resource_type = publish_request.resource_type
            resource_doc.language = language
            resource_doc.save()

    @property
    def data(self):
        return [
            resource.data
            for resource in self.officialresource_set.order_by("language__code")
        ]

    def __str__(self):
        return "({0}) {1}".format(self.short_name, self.long_name)


@reversion.register()
class OfficialResource(models.Model):
    language = models.ForeignKey(Language, related_name="official_resources", verbose_name="Language")
    resource_type = models.ForeignKey(OfficialResourceType, verbose_name="Official resource type")
    contact = models.ForeignKey(Contact, related_name="official_resources", null=True, blank=True)
    date_started = models.DateField()
    notes = models.TextField(blank=True)
    offline = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    # Publishing
    publish_date = models.DateField(null=True, blank=True)
    version = models.CharField(max_length=10, blank=True)
    source_text = models.ForeignKey(Language, null=True, blank=True, related_name="+")
    source_version = models.CharField(max_length=10, blank=True)
    checking_entity = models.ManyToManyField(Organization, related_name="resource_publications", blank=True)
    contributors = models.ManyToManyField(Contact, related_name="+", blank=True)
    checking_level = models.IntegerField(choices=CHECKING_LEVEL_CHOICES, null=True, blank=True)

    def ingest(self, publish_request):
        self.resource_type.ingest(self.language, publish_request)

    @property
    def data(self):
        """
        {
            "date_modified": "20150826",
            "direction": "ltr",
            "language": "en",
            "status": {
                "checking_entity": "Distant Shores Media; Wycliffe Associates",
                "checking_level": "3",
                "comments": "Original source text.",
                "contributors": "Distant Shores Media",
                "publish_date": "2015-08-26",
                "source_text": "en",
                "source_text_version": "4",
                "version": "4"
            },
            "string": "English"
        }
        """
        return {
            "date_modified": self.created,
            "direction": self.language.get_direction_display(),
            "language": self.language.code,
            "string": self.language.name,
            "status": {
                "checking_entity": self.checking_entity.name if self.checking_entity else "",
                "checking_level": self.checking_level,
                "comments": "\n\n".join([
                    comment.comment
                    for comment in self.comments.order_by("created_at")
                ]),
                "contributors": ", ".join([
                    contact.name
                    for contact in self.contributors.order_by("name")
                ]),
                "publish_date": self.publish_date.strftime("%Y-%m-%d") if self.publish_date else "",
                "source_text": self.source_text.code if self.source_text else "",
                "source_text_version": self.source_version,
                "version": self.version
            }
        }

    def versions(self):
        return reversion.get_for_object(self)

    class Meta:
        ordering = ["language", "contact"]

    def __unicode__(self):
        return "({code}) {resource_type} {version}".format(
            code=self.language.code,
            resource_type=self.resource_type.long_name,
            version=self.version
        )


class Comment(models.Model):
    official_resource = models.ForeignKey(OfficialResource, related_name="comments", null=True)
    comment = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)


@python_2_unicode_compatible
class PublishRequest(models.Model):
    requestor = models.CharField(max_length=100, verbose_name="Requester name")
    resource_type = models.ForeignKey(OfficialResourceType, null=True, verbose_name='Official resource type')
    language = models.ForeignKey(Language, related_name="publish_requests")
    checking_level = models.IntegerField(choices=CHECKING_LEVEL_CHOICES, verbose_name="Requested checking level")
    source_text = models.ForeignKey(Language, related_name="source_publish_requests", null=True)
    source_version = models.CharField(max_length=10, blank=True)
    contributors = models.TextField(blank=True, help_text="Names or Pseudonyms")
    created_at = models.DateTimeField(default=timezone.now)
    approved_at = models.DateTimeField(default=None, blank=True, null=True, db_index=True)
    requestor_email = models.EmailField(blank=True,
                                        default="",
                                        verbose_name="Requester email",
                                        help_text="email address to be notified of request status")
    license_title = models.TextField(default="CC BY-SA 4.0", blank=True, null=False)
    rejected_at = models.DateTimeField(default=None, null=True, blank=True, verbose_name="Rejected at")
    rejected_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, null=True, blank=True,
                                    verbose_name="Rejected by")

    @property
    def permalink(self):
        if self.pk is None:
            return None

        return base64.urlsafe_b64encode(unicode(self.pk).zfill(6))

    @property
    def version(self):
        parts = self.source_version.split(".")
        if len(parts) == 3:
            return ".".join([parts[0], str(int(parts[1]) + 1), parts[2]])
        else:
            return "invalid"

    @property
    def data(self):
        return {
            "mod": self.created_at.strftime("%s"),
            "direction": self.language.get_direction_display(),
            "lc": self.language.code,
            "name": self.language.name,
            "status": {
                "checking_entity": "",  # orgs aren't being added to resources
                "checking_level": self.checking_level,

td/publishing/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}


<ul class="nav navbar-nav pull-right">
    {% if request.user.is_authenticated %}
        <p class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </p>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i> {% trans "Settings" %}</a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i> {% trans "Log out" %}</a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

td/publishing/templates/_footer.html
{% load i18n %}

{% trans "&copy; 2015 unfoldingWord" %}

td/publishing/templates/contact_create.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}Create Contact{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">Home</a></li>
        <li><a href="{% url "contact_list" %}">Contacts</a></li>
        <li>Create</li>
    </ul>

    <h1>Create Contact</h1>
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-4">
                <form action="" method="post">{% csrf_token %}
                    {{ form|bootstrap }}
                    <button type="submit" class="btn btn-primary"><i class="fa fa-user"></i> Create</button>
                </form>
            </div>
        </div>
        {% else %}
            {% url "account_login" as login_url %}
            <p>{% blocktrans %}
                Login to get started.
                <a href="{{ login_url }}" class="btn btn-default">Log In</a>
            </p>{% endblocktrans %}
        {% endif %}
        </div>
    </section>
{% endblock %}

td/publishing/templates/contact_detail.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{{ object.name }}{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">Home</a></li>
        <li><a href="{% url "contact_list" %}">Contacts</a></li>
        <li>{{ object.name }}</li>
    </ul>

    <h1>{{ object.name }}</h1>
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-4">
                <div>
                <p>
                    <a href="/contacts/{{ object.id}}/update/">
                        <button class="btn btn-primary">
                            <i class="fa fa-edit"></i>
                            Edit</button></a>
                    | <a href="mailto:{{ object.email }}">
                        <i class="fa fa-send"></i>
                        {{ object.email }}
                    </a>
                </p>
                <p><b>{{ object.d43username }}</b> @ <a href="https://door43.org" target="_blank">door43.org</a></p>
                <p>Location: {{ object.location  }}</p>
                <p>Phone: {{ object.phone  }}</p>
                <p>Languages: {{  object.languages.all|join:", " }}</p>
                <p>Organizations: {{ object.org.all|join:", " }}</p>
                <p>Other: {{ object.other  }}</p>
                <!-- <p>Checking Entity: {% if object.checking_entity %}
                                    <i class="fa fa-check"></i>
                                    {% else %}
                                    <i class="fa fa-remove"></i>
                                    {% endif %}</p> -->
                </div>
                <div>
                <h3>Connections</h3>
                {% if con_success %}
                  <div class="alert alert-success">
                      <a href="#" class="close" data-dismiss="alert">&times;</a>
                      <p>{{ con_success }}</p>
                  </div>
                {% endif %}
                {% if connections %}
                    {% for con in connections  %}
                        <p><a href="/contacts/{{ con.con_dst.id }}">
                            {{ con.con_dst }} - {{ con.con_type }}
                        </a></p>
                        {% endfor %}
                {% endif %}
                    <form action="" method="post" class="form">
                        {% csrf_token %}
                        {{ form_con|bootstrap }}
                        <button type="submit" class="btn btn-primary" name="con">
                            <i class="fa fa-plus"></i> New
                        </button>
                    </form>
                </div>
            </div>
            <div class="col-md-6">
                <h2>Recent Messages</h2>
                {% if com_success %}
                  <div class="alert alert-success">
                      <a href="#" class="close" data-dismiss="alert">&times;</a>
                      <p>{{ com_success }}</p>
                  </div>
                {% endif %}
                {% if recent_coms %}
                <table class="table table-striped">
                    <thead>
                        <tr>
                            <th>Message</th>
                            <th>Added By</th>
                            <th>Datestamp</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for com in recent_coms  %}
                        <tr>
                            <td> <p> {{ com.communication }} </p> </td>
                            <td> {{ com.created_by.username }} </td>
                            <td> {{ com.created }} </td>
                        </tr>
                        {% endfor %}
                    </tbody>
                </table>
                {% else %}
                <p>None, add one!</p>
                {% endif %}
                <div>
                    <form action="" method="post" class="form">
                        {% csrf_token %}
                        {{ form_com|bootstrap }}
                        <button type="submit" class="btn btn-primary" name="recent_com">
                            <i class="fa fa-comment"></i> Add
                        </button>
                    </form>
                </div>
            </div>
        </div>
    {% else %}
        {% url "account_login" as login_url %}
        <p>{% blocktrans %}
            Login to get started.
            <a href="{{ login_url }}" class="btn btn-default">Log In</a>
        </p>{% endblocktrans %}
    {% endif %}
{% endblock %}

td/publishing/templates/contact_update.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}Update {{ object.name }}{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">Home</a></li>
        <li><a href="{% url "contact_list" %}">Contacts</a></li>
        <li><a href="{% url "contact_detail" object.pk %}">{{ object.name }}</a></li>
    </ul>

    <h1>Edit {{ object.name }}</h1>
    {% if user.is_authenticated %}
        <div class="row">
            <div class="col-md-4">
                <form action="" method="post">{% csrf_token %}
                    {{ form|bootstrap }}
                    <button type="submit" class="btn btn-primary"><i class="fa fa-comment"></i> Update</button>
                </form>
            </div>
        </div>
    {% else %}
            {% url "account_login" as login_url %}
            <p>{% blocktrans %}
                Login to get started.
                <a href="{{ login_url }}" class="btn btn-default">Log In</a>
            </p>{% endblocktrans %}
    {% endif %}
{% endblock %}

td/publishing/templates/contacts.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Contacts{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">Home</a></li>
        <li>Contacts</li>
    </ul>

    <h1>{% trans "Contacts" %}</h1>
    <div class="row">
        <div class="col-md-4">
            <div class="input-group">
                <span class="input-group-addon"><i class="fa fa-user"></i></span>
                <input type="text" class="form-control" id="contacts" placeholder="Search...">
            </div>
        </div>
        <div class="col-md-2">
        </div>
        <div class="col-md-4">
            <a href="/contacts/create/"><button class="btn btn-primary"><i class="fa fa-user"></i> Create</button></a>
        </div>
    </div>
{% endblock %}

td/publishing/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load staticfiles %}
{% load metron_tags %} {% load i18n %}


{% block style_base %}
    <link href="{% static "pinax/css/theme.css" %}" rel="stylesheet">
    <link href="{% static "css/site.css" %}" rel="stylesheet">
    <link href="https://code.jquery.com/ui/1.11.2/themes/smoothness/jquery-ui.css" rel="stylesheet">
    <link rel="stylesheet" href="{% static "select2-3.5.2/select2.css" %}">
    <link rel="stylesheet" href="{% static "select2-3.5.2/select2-bootstrap.css" %}">
    {% block extra_style %}{% endblock %}
{% endblock %}


{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}

{% block nav %}
    {% if user.is_authenticated %}
    <ul class="nav navbar-nav">
        <li>
            <a href="{% url "contact_list" %}"><i class="fa fa-group"></i> Contacts</a>
        </li>
        <li>
            <a href="{% url "obs_list" %}"><i class="fa fa-cogs"></i> OBS Records</a>
        </li>
    </ul>
    {% else %}
    <ul class="nav navbar-nav">
        <li>
            <a href="https://docs.google.com/a/sil.org/forms/d/1WWbIZkDT0-mwr1LzYdnxZq2S4gzMg7PbxL8MjFReHFE/viewform"><i class="fa fa-th"></i> Request Publication</a>
        </li>
    </ul>
    {% endif %}
{% endblock %}


{% block script_base %}
    {{ block.super }}
    <script src="https://code.jquery.com/ui/1.11.2/jquery-ui.min.js"></script>
    <script type="text/javascript">
        $(function() {
            $("#contacts").autocomplete({
              source: "{% url "api_contacts" %}",
              minLength: 2,
              select: function( event, ui ) {
                  window.location.href = ui.item.url;
              }
            });
        });
        $(function() {
            $( "#id_date_started" ).datepicker();
        });
        $(function() {
            $( "#id_publish_date" ).datepicker();
        });
        $(function() {
            $("#contacts-id").autocomplete({
              source: "{% url "api_contacts" %}",
              minLength: 2
            });
        });
    </script>
    <script src="{% static "select2-3.5.2/select2.min.js" %}"></script>
    <script src="{% static "js/app.js" %}"></script>
    {% block extra_script %}{% endblock %}
{% endblock %}