td/api/urls.py
from django.conf.urls import url

from .views import (
    celerybeat_healthz,
    lang_assignment_changed_json,
    lang_assignment_json,
    QuestionnaireView,
    templanguages_json
)


urlpatterns = [
    url(r"^questionnaire/$", QuestionnaireView.as_view(), name="questionnaire"),
    url(r"^templanguages/$", templanguages_json, name="templanguages"),
    url(r"^templanguages/assignment/$", lang_assignment_json, name="templanguages_assignment"),
    url(r"^templanguages/assignment/changed/$", lang_assignment_changed_json, name="templanguages_changed"),
    url(r"^celerybeat/healthz/$", celerybeat_healthz),
]

td/commenting/urls.py
from django.conf.urls import url

from .views import PostCommentView, DeleteCommentView


urlpatterns = [
    url(r"^post/$", PostCommentView.as_view(), name="post_comment"),
    url(r"^delete/(?P<id>\d+)/$", DeleteCommentView.as_view(), name="delete_comment"),
]

td/resources/urls.py
from django.conf.urls import url

from .views import (
    PublisherListView,
    PublisherDetailView,
    PublisherEditView,
    PublisherCreateView,
    TitleListView,
    TitleDetailView,
    TitleEditView,
    TitleCreateView,
    TempLanguageQuestionnaireView,
)

urlpatterns = [
    url(r"publishers/$", PublisherListView.as_view(), name="publisher_list"),
    url(r"publishers/create/$", PublisherCreateView.as_view(), name="publisher_create"),
    url(r"publishers/(?P<pk>\d+)/$", PublisherDetailView.as_view(), name="publisher_detail"),
    url(r"publishers/(?P<pk>\d+)/edit/$", PublisherEditView.as_view(), name="publisher_edit"),
    url(r"titles/$", TitleListView.as_view(), name="title_list"),
    url(r"titles/create/$", TitleCreateView.as_view(), name="title_create"),
    url(r"titles/(?P<slug>[-\w\d]+)/$", TitleDetailView.as_view(), name="title_detail"),
    url(r"titles/(?P<slug>[-\w\d]+)/edit/$", TitleEditView.as_view(), name="title_edit"),

    url(r"^questionnaire/(?P<temp_language>\d+)/$", TempLanguageQuestionnaireView.as_view(), name="templanguage_questionnaire"),
]

td/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin

from .views import (
    HomeView,
    AdditionalLanguageListView,
    EthnologueCountryCodeListView,
    EthnologueLanguageCodeListView,
    EthnologueLanguageIndexListView,
    SIL_ISO_639_3ListView,
    WikipediaISOLanguageListView,
    IMBPeopleGroupListView,
    AjaxAdditionalLanguageListView,
    AjaxEthnologueCountryCodeListView,
    AjaxEthnologueLanguageCodeListView,
    AjaxEthnologueLanguageIndexListView,
    AjaxSIL_ISO_639_3ListView,
    AjaxWikipediaISOLanguageListView,
    AjaxIMBPeopleGroupListView,
    codes_text_export,
    names_text_export,
    names_json_export,
    names_json_export_short,
    export_svg,
    languages_autocomplete,
    gateway_languages_autocomplete,
)

urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^siteadmin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^invites/", include("pinax.invitations.urls")),

    url(r"^exports/codes-d43.txt$", codes_text_export, name="codes_text_export"),
    url(r"^exports/langnames.txt$", names_text_export, name="names_text_export"),
    url(r"^exports/langnames.json$", names_json_export, name="names_json_export"),
    url(r"^exports/langnames_short.json$", names_json_export_short, name="names_json_export_short"),
    url(r"^exports/gatewaylanguages-map/$", export_svg, name="gateway_languages_map_export"),

    url(r"^uw/", include("td.resources.urls")),
    url(r"^uw/", include("td.urls_languages")),

    url(r"^publishing/", include("td.publishing.urls")),
    url(r"^api/", include("td.urls_api")),
    url(r"^api/", include("td.api.urls", namespace="api")),
    url(r"^comment/", include("td.commenting.urls", namespace="comment")),
    url(r"^comments/", include("django_comments.urls")),

    url(r"^data-sources/additional-languages/$", AdditionalLanguageListView.as_view(), name="ds_additional_languages"),
    url(r"^data-sources/ethnologue/country-codes/$", EthnologueCountryCodeListView.as_view(), name="ds_ethnologue_country_codes"),
    url(r"^data-sources/ethnologue/language-codes/$", EthnologueLanguageCodeListView.as_view(), name="ds_ethnologue_language_codes"),
    url(r"^data-sources/ethnologue/language-index/$", EthnologueLanguageIndexListView.as_view(), name="ds_ethnologue_language_index"),
    url(r"^data-sources/sil-iso-639-3/$", SIL_ISO_639_3ListView.as_view(), name="ds_sil"),
    url(r"^data-sources/wikipedia/$", WikipediaISOLanguageListView.as_view(), name="ds_wikipedia"),
    url(r"^data-sources/imb/peoplegroups/$", IMBPeopleGroupListView.as_view(), name="ds_imb_peoplegroups"),

    url(r"^ajax/data-sources/additional-languages/$", AjaxAdditionalLanguageListView.as_view(), name="ajax_ds_additional_languages"),
    url(r"^ajax/data-sources/ethnologue/country-codes/$", AjaxEthnologueCountryCodeListView.as_view(), name="ajax_ds_ethnologue_country_codes"),
    url(r"^ajax/data-sources/ethnologue/language-codes/$", AjaxEthnologueLanguageCodeListView.as_view(), name="ajax_ds_ethnologue_language_codes"),
    url(r"^ajax/data-sources/ethnologue/language-index/$", AjaxEthnologueLanguageIndexListView.as_view(), name="ajax_ds_ethnologue_language_index"),
    url(r"^ajax/data-sources/sil-iso-639-3/$", AjaxSIL_ISO_639_3ListView.as_view(), name="ajax_ds_sil"),
    url(r"^ajax/data-sources/wikipedia/$", AjaxWikipediaISOLanguageListView.as_view(), name="ajax_ds_wikipedia"),
    url(r"^ajax/data-sources/imb/peoplegroups/$", AjaxIMBPeopleGroupListView.as_view(), name="ajax_ds_imb_peoplegroups"),

    url(r"^ac/langnames/", languages_autocomplete, name="names_autocomplete"),
    url(r"^ac/gateway-langnames/", gateway_languages_autocomplete, name="gateway_languages")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

td/models.py
from __future__ import unicode_literals

from django.contrib.contenttypes.models import ContentType
from django.contrib.auth.models import User
from django.core.urlresolvers import reverse
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from collections import defaultdict

from jsonfield import JSONField
from model_utils import FieldTracker

from td.commenting.models import CommentableModel
from .gl_tracking.models import Document


DIRECTION_CHOICES = (
    ("l", "ltr"),
    ("r", "rtl")
)


@python_2_unicode_compatible
class JSONData(models.Model):
    created = models.DateTimeField(auto_now_add=True)
    modified = models.DateTimeField(auto_now=True)
    name = models.SlugField(max_length=50)
    data = JSONField()

    def __str__(self):
        return self.name


@python_2_unicode_compatible
class TempLanguage(models.Model):
    APP_CHOICES = (
        ("td", "translationDatabase"),
        ("ts-android", "translationStudio Android"),
        ("ts-desktop", "translationStudio Desktop"),
        ("tr", "translationRecorder"),
    )
    STATUS_CHOICES = (
        ("p", "Pending"),
        ("a", "Approved"),
        ("r", "Rejected"),
    )
    code = models.CharField(max_length=12, unique=True)
    name = models.CharField(max_length=200, blank=True)
    country = models.ForeignKey("Country", on_delete=models.SET_NULL, null=True)
    direction = models.CharField(max_length=1, choices=DIRECTION_CHOICES, default="l")
    app = models.CharField(max_length=10, choices=APP_CHOICES, blank=True)
    requester = models.CharField(max_length=100)
    questionnaire = models.ForeignKey("resources.Questionnaire", on_delete=models.PROTECT, null=True)
    answers = JSONField(blank=True)
    request_id = models.SlugField(max_length=50, blank=True)
    status = models.CharField(max_length=1, choices=STATUS_CHOICES, default="p")
    status_comment = models.TextField(blank=True)
    lang_assigned = models.OneToOneField("Language", on_delete=models.SET_NULL, null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="templanguage_created", null=True,
                                   blank=True, editable=False)
    modified_at = models.DateTimeField(auto_now=True)
    modified_by = models.ForeignKey(User, on_delete=models.SET_NULL, related_name="templanguage_modified", null=True,
                                    blank=True, editable=False)

    def __str__(self):
        return self.code

    def get_absolute_url(self):
        return reverse('templanguage_detail', args=[str(self.id)])

    @property
    def lang_assigned_url(self):
        return reverse('language_detail', args=[str(self.lang_assigned_id)]) if self.lang_assigned_id else ""

    @property
    def questions_and_answers(self):
        answers = {}
        if self.answers is not None:
            for a in self.answers:
                answers[str(a["question_id"])] = a["text"]
        questions = []
        # Build a list of questions
        for q in self.questionnaire.questions:
            if str(q["id"]) in answers:
                question_answer = answers[str(q["id"])]
            else:
                question_answer = ""
            questions.append({"id": q["id"], "question": q["text"], "answer": question_answer})
        # Now match in the answers
        return questions

    @classmethod
    def pending(cls):
        return cls.objects.filter(status="p")

    @classmethod
    def approved(cls):
        return cls.objects.filter(status="a")

    @classmethod
    def rejected(cls):
        return cls.objects.filter(status="r")

    @classmethod
    def lang_assigned_data(cls):
        return [{"pk": x.pk, "lc": x.code, "ln": x.name, "ang": x.lang_assigned and x.lang_assigned.ang,
                 "alt": x.lang_assigned and x.lang_assigned.alt_name_all, "cc": [x.country.code] if x.country else [],
                 "lr": x.lang_assigned and x.lang_assigned.lr, "gw": x.lang_assigned and x.lang_assigned.gateway_flag,
                 "ld": x.get_direction_display()} for x in cls.objects.all().select_related("lang_assigned", "country")]

    @classmethod
    def lang_assigned_map(cls):
        return [{x.code: x.lang_assigned.lc} for x in cls.objects.all() if x.lang_assigned is not None]

    @classmethod
    def lang_assigned_changed_map(cls):
        return [{x.code: x.lang_assigned.lc}
                for x in cls.objects.all() if x.lang_assigned is not None and x.code != x.lang_assigned.lc]


@python_2_unicode_compatible
class AdditionalLanguage(models.Model):
    ietf_tag = models.CharField(max_length=100)
    common_name = models.CharField(max_length=100)
    two_letter = models.CharField(max_length=2, blank=True)
    three_letter = models.CharField(max_length=3, blank=True)
    native_name = models.CharField(max_length=100, blank=True)
    direction = models.CharField(max_length=1, choices=DIRECTION_CHOICES, default="l")
    comment = models.TextField(blank=True)
    created_at = models.DateTimeField(default=timezone.now)
    updated_at = models.DateTimeField(default=timezone.now)

    def merge_code(self):
        return self.two_letter or self.three_letter or self.ietf_tag

    def merge_name(self):
        return self.native_name or self.common_name

    def save(self, *args, **kwargs):
        self.updated_at = timezone.now()
        return super(AdditionalLanguage, self).save(*args, **kwargs)

    def __str__(self):
        return self.ietf_tag

    class Meta:
        verbose_name = "Additional Language"


@python_2_unicode_compatible
class Network(models.Model):
    name = models.CharField(max_length=100)

    def get_absolute_url(self):
        return reverse("network_detail", args=[self.pk])

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'uw_network'


@python_2_unicode_compatible
class Region(models.Model):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    tracker = FieldTracker()

    def __str__(self):
        return self.name

    class Meta:
        db_table = 'uw_region'
        ordering = ['name']


@python_2_unicode_compatible
class WARegion(CommentableModel):
    name = models.CharField(max_length=100, db_index=True)
    slug = models.SlugField(max_length=100, db_index=True)
    tracker = FieldTracker()

    class Meta:
        db_table = 'wa_region'
        ordering = ['name']

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("wa_region_detail", kwargs={"slug": self.slug})

    @property
    def gl_directors(self):
        return [d.name for d in self.gldirector_set.filter(is_helper=False)]

    @property
    def gl_helpers(self):
        return [d.name for d in self.gldirector_set.filter(is_helper=True)]

    @property
    def tag_slug(self):
        return self.slug

    @property
    def tag_tip(self):
        return ""

    @classmethod
    def slug_all(cls):
        return list(WARegion.objects.all().values_list("slug", flat=True))


@python_2_unicode_compatible
class Country(CommentableModel):
    code = models.CharField(max_length=2, unique=True)
    alpha_3_code = models.CharField(max_length=3, blank=True, default="")
    name = models.CharField(max_length=75)
    region = models.ForeignKey(Region, null=True, blank=True, related_name="countries")
    wa_region = models.ForeignKey(WARegion, null=True, blank=True, on_delete=models.SET_NULL)
    population = models.IntegerField(null=True, blank=True)
    primary_networks = models.ManyToManyField(Network, blank=True, db_table='uw_country_primary_networks')
    extra_data = JSONField(default=dict)

    tracker = FieldTracker()

    class Meta:
        db_table = 'uw_country'

    def gateway_language(self):
        if not hasattr(self, "_gateway_language"):
            data = self.extra_data
            if not isinstance(data, dict):
                data = {}
            self._gateway_language = next(iter(Language.objects.filter(code=data.get("gateway_language"))), None)
        return self._gateway_language

    def gateway_languages(self, with_primary=True):
        gl = self.gateway_language()
        if gl:
            ogls = [gl]
        else:
            ogls = []
        for lang in self.language_set.all():
            if lang.gateway_flag and lang not in ogls:
                ogls.append(lang)
            elif lang.gateway_language and lang.gateway_language not in ogls:
                ogls.append(lang.gateway_language)
        if not with_primary and gl:
            ogls.remove(gl)
        return ogls

    @classmethod
    def regions(cls):
        qs = cls.objects.all().values_list("region", flat=True).distinct()
        qs = qs.order_by("region.name")
        return qs

    @classmethod
    def gateway_data(cls):
        with_gateways = cls.objects.filter(language__gateway_language__isnull=False).distinct()
        without_gateways = cls.objects.exclude(pk__in=with_gateways)
        data = {
            x.code: {"obj": x, "gateways": defaultdict(lambda: [])}
            for x in with_gateways
        }
        data.update({
            x.code: {"obj": x, "gateways": {"n/a": list(x.language_set.all())}}
            for x in without_gateways
        })
        for country in with_gateways:
            for lang in country.language_set.all():
                if lang.gateway_language:
                    data[country.code]["gateways"][lang.gateway_language.code].append(lang)
                else:
                    data[country.code]["gateways"]["n/a"].append(lang)
        return data

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("country_detail", kwargs={"pk": self.pk})


@python_2_unicode_compatible
class LanguageAltName(models.Model):

td/commenting/forms.py
import re

from django_comments.forms import CommentForm

from td.commenting.models import CommentTag


class CommentFormWithTags(CommentForm):

    def __init__(self, *args, **kwargs):
        super(CommentFormWithTags, self).__init__(*args, **kwargs)
        comment_textarea = self.fields["comment"].widget
        comment_textarea.attrs["rows"] = "3"
        comment_textarea.attrs["placeholder"] = "Type a comment here..."

    def process_tags(self):
        comment = self.cleaned_data.get("comment")
        tags = [part.replace("#", "") for part in comment.split() if "#" in part]
        valid_tags = []

        for tag in tags:
            tag = re.sub(r"[\s.,\?\!\;\:\'\"\(\)]*", "", tag)
            try:
                tag_object = CommentTag.objects.get(slug=tag)
                tag_in_comment = r"#" + tag + "(?=[\s.,\?\!\;\:\'\"\(\)]|$)"
                comment = re.sub(r"%s" % tag_in_comment, tag_object.html, comment)
                tag not in valid_tags and valid_tags.append(tag)
            except CommentTag.DoesNotExist:
                # If tag is invalid, don't pick it up
                pass

        return comment, valid_tags

td/templates/_account_bar.html
{% load i18n %}
{% load account_tags %}

<ul class="nav navbar-nav navbar-right">
    {% if request.user.is_authenticated %}
        <p class="navbar-text">
            <i class="fa fa-user"></i> {% user_display request.user %}
        </p>
        <li>
            <a href="{% url 'account_settings' %}"><i class="fa fa-cog"></i></a>
        </li>
        <li>
            <a id="account_logout" href="{% url 'account_logout' %}"><i class="fa fa-power-off"></i></a>
        </li>
    {% else %}
        <li><a href="{% url 'account_login' %}">{% trans "Log in" %}</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li><a href="{% url 'account_signup' %}">{% trans "Sign up" %}</a></li>
        {% endif %}
    {% endif %}
</ul>

<form id="accountLogOutForm" style="display: none;" action="{% url 'account_logout' %}" method="POST">
    {% csrf_token %}
</form>

td/templates/_footer.html
{% load i18n %}

<p>
    {% blocktrans %}
    translationDatabase is an <a href="https://unfoldingword.org/">unfoldingWord</a>
    project
    {% endblocktrans %}
</p>

<p>
    {% blocktrans %}
    All original language identification content in translationDatabase is available under a
    <a href="http://creativecommons.org/licenses/by-sa/4.0">
        Creative Commons Attribution-ShareAlike License
    </a>.
    {% endblocktrans %}
</p>

<a rel="license" href="http://creativecommons.org/licenses/by-sa/4.0/">
    <img alt="{% trans "Creative Commons License" %}" style="border-width:0" src="https://i.creativecommons.org/l/by-sa/4.0/88x31.png" />
</a>

td/templates/_loading.html
<div class="loading">
  <div class="spinner">
    <div class="rect1"></div>
    <div class="rect2"></div>
    <div class="rect3"></div>
    <div class="rect4"></div>
    <div class="rect5"></div>
  </div>
</div>

td/templates/_messages.html
{% load pinax_theme_bootstrap_tags %}
{% for message in messages %}
    <div class="alert fade in {% get_message_tags message %}">
        <button type="button" class="close" data-dismiss="alert">&times;</button>
        {{ message }}
    </div>
{% endfor %}
<div class="alert fade in alert-danger">
    <p style="margin-bottom: 2.0rem;">Dear users,</p>
    <p style="margin-bottom: 2.0rem;">We regret to inform you that translationDatabase will be decommissioned soon. After careful consideration, we have decided to discontinue this website and focus our efforts on other projects.</p>
    <p>Effective from August 31st, the main website will no longer be available, and you will be forwarded to <a href='http://openlanguages.io/'>openlanguages.io</a> instead. This website is currently under construction. The basic language name and code information found at <a href='http://td.unfoldingword.org/exports/langnames.json'>td.unfoldingword.org/exports/langnames.json</a> will remain at that location for compatibility. You may continue to point applications at that endpoint for basic language information.</p>
</div>

td/templates/_scripts.html
<script src='/site_media/static/js/site.js?628d1571641a8961c3f0'></script>

td/templates/_styles.html
<link href='/site_media/static/css/site.css?628d1571641a8961c3f0' rel='stylesheet' />

td/templates/banner_base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body %}

    <div>
        {% block content %}
        {% endblock %}
    </div>

    <div class="center-text">
        {% block banner %}
            <h1>Hello, world!</h1>
            <p>Vestibulum id ligula porta felis euismod semper. Integer posuere erat a ante venenatis dapibus posuere velit aliquet. Duis mollis, est non commodo luctus, nisi erat porttitor ligula, eget lacinia odio sem nec elit.</p>
            <p><a class="btn btn-primary btn-large">Learn more &raquo;</a></p>
        {% endblock %}
    </div>

{% endblock %}

td/templates/homepage.html
{% extends "banner_base.html" %}

{% load staticfiles %}
{% load i18n %}


{% block head_title %}{% trans "Home" %}{% endblock %}


{% block body_class %}home{% endblock %}


{% block content %}
    <div class="center-text">
        <h2><label for="query">Search for a Language</label></h2>
        <form action="{% url "language_list" %}" method="GET">
            <input name="q" class="giant-search-input" type="text" placeholder="any keyword" required>
            <button type="submit" class="giant-search-submit"><i class="fa fa-search fa-lg"></i></button>
        </form>
    </div>

    <hr>

    <div class="center-text clearfix">
        <h2 class="floating-map-title center-text">Gateway Languages</h2>
        <p>Download as <a class="link clickable btn-export-map">PDF <i class="fa fa-download"></i></a></p>
        <div id="mapcontainer" class="col-lg-12 col-md-12 col-sm-12">
        </div>
    </div>

    <hr>
{% endblock %}


{% block banner %}
    <h2>{% trans "End the spiritual famine" %}</h2>
    {% blocktrans %}
        <div>
            Help <a href="http://door43.org/en/get-started" class="btn btn-primary">translate</a> or <a href="https://unfoldingword.org/give/" class="btn btn-primary">donate</a> to a project.
        </div>
    {% endblocktrans %}
{% endblock %}


{% block custom_bottom_script %}
    <!-- Hidden <FORM> to submit the SVG data to the server, which will convert it to SVG/PDF/PNG downloadable file.
     The form is populated and submitted by the JavaScript below. -->
    <form id="svgform" method="post" action="{% url "gateway_languages_map_export" %}">
      <input type="hidden" id="output_format" name="output_format" value="">
      <input type="hidden" id="data" name="data" value="">
    </form>
{% endblock %}

td/templates/site_base.html
{% extends "theme_bootstrap/base.html" %}

{% load pinax_invitations_tags %}
{% load staticfiles %}
{% load metron_tags %}
{% load i18n %}
{% load user_group %}


{% block styles %}
    <link href='https://fonts.googleapis.com/css?family=Merriweather+Sans:400,700,300' rel='stylesheet' type='text/css'>
    {% include "_styles.html" %}
    {% block extra_style %}{% endblock %}
    <style>
        .tt-query,
        .tt-hint {
            width: 396px;
            height: 30px;
            padding: 8px 12px;
            font-size: 24px;
            line-height: 30px;
            border: 2px solid #ccc;
            border-radius: 8px;
            outline: none;
        }

        .tt-query {
            box-shadow: inset 0 1px 1px rgba(0, 0, 0, 0.075);
        }

        .tt-hint {
            color: #999;
        }

        .tt-dropdown-menu {
            width: 550px;
            margin-top: 12px;
            padding: 8px 0;
            background-color: #fff;
            border: 1px solid #ccc;
            border: 1px solid rgba(0, 0, 0, 0.2);
            border-radius: 8px;
            box-shadow: 0 5px 10px rgba(0,0,0,.2);
        }

        .tt-suggestion {
            padding: 3px 20px;
            font-size: 18px;
            line-height: 24px;
        }

        .tt-suggestion.tt-cursor {
            color: #fff;
            background-color: #0097cf;

        }

        .tt-suggestion p {
            margin: 0;
        }
        .tt-highlight {
          color: #99E;
        }
        .tt-suggestion code {
          padding: 2px 4px;
          font-size: 80%;
          color: #c7254e;
          background-color: #f9f2f4;
          white-space: nowrap;
          border-radius: 4px;
          font-family: Monaco,Menlo,Consolas,"Courier New",monospace;
        }
        #remote .empty-message {
          padding: 5px 10px;
          text-align: center;
        }
        input {
          padding: 10px;
          width: 600px;
          font-size: 24px;
          border: 1px solid #AAA;
        }
        #remote {
          width: 600px;
          margin-top: 100px;
          margin-right: auto;
          margin-left: auto;
        }
        li.exclusive {
            background-color: #D9EDF7;
        }
        </style>
{% endblock %}


{% block nav %}
    <ul class="nav navbar-nav">
        <li class="dropdown data-sources">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-database"></i>
                Data Sources
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li class="dropdown-header"><i class="fa fa-pencil"></i> Created</li>
                <li><a href="{% url "ds_additional_languages" %}">Additional Languages</a></li>
                <li class="divider"></li>
                <li class="dropdown-header"><i class="fa fa-database"></i> Imports</li>
                <li><a href="{% url "ds_ethnologue_country_codes" %}">Country Codes <em>Ethnologue</em></a></li>
                <li><a href="{% url "ds_ethnologue_language_codes" %}">Language Codes <em>Ethnologue</em></a></li>
                <li><a href="{% url "ds_ethnologue_language_index" %}">Language Index <em>Ethnologue</em></a></li>
                <li><a href="{% url "ds_sil" %}">ISO 639-3 Code Set <em>SIL</em></a></li>
                <li><a href="{% url "ds_wikipedia" %}">List of ISO 639-1 Codes <em>Wikipedia</em></a></li>
                <li><a href="{% url "ds_imb_peoplegroups" %}">People Groups <em>IMB</em></a></li>
                <li class="divider"></li>
                <li class="dropdown-header"><i class="fa fa-database"></i> Exports</li>
                <li><a href="{% url "codes_text_export" %}">Language Codes<em>codes-d43.txt</em></a></li>
                <li><a href="{% url "names_text_export" %}">Language Names<em>langnames.txt</em></a></li>
                <li><a href="{% url "names_json_export" %}">Language Names JSON<em>langnames.json</em></a></li>
            </ul>
        </li>

        <li class="dropdown uw">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-sign-in"></i>
                uW
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                <li><a href="{% url "language_list" %}">Languages</a></li>
                <li><a href="{% url "region_list" %}">Regions</a></li>
                <li><a href="{% url "country_list" %}">Countries</a></li>
                <li><a href="{% url "title_list" %}">Titles</a></li>
                <li><a href="{% url "publisher_list" %}">Publishers</a></li>
                <li><a href="{% url "network_list" %}">Networks</a></li>
                {% if user.is_authenticated %}
                    <li class="divider"></li>
                    <li><a href="{% url "gateway_flag_update" %}">Update Gateway Languages</a></li>
                    <li><a href="{% url "rtl_languages_update" %}">Update RTL Languages (Scripts)</a></li>
                {% endif %}
            </ul>
        </li>

        {% if not user.is_authenticated or user|has_group:"Publishing" %}
        <li class="dropdown publishing">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                <i class="fa fa-book"></i>
                Publishing
                <span class="caret"></span>
            </a>
            <ul class="dropdown-menu" role="menu">
                {% if user.is_authenticated %}
                <li><a href="{% url "publishing_home" %}">Publishing Home</a></li>
                {% else %}
                <li><a href="https://docs.google.com/a/sil.org/forms/d/1WWbIZkDT0-mwr1LzYdnxZq2S4gzMg7PbxL8MjFReHFE/viewform">Publish Request</a></li>
                {% endif %}
            </ul>
        </li>
        {% endif %}
    </ul>
    {% invite_form request.user %}
{% endblock %}


{% block extra_head_base %}
    <link rel="shortcut icon" href="{% static "images/favicon.ico" %}"/>
    {% block extra_head %}{% endblock %}
{% endblock %}


{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}


{% block footer %}
    {% include "_footer.html" %}
{% endblock %}


{% block scripts %}
    {% include "_scripts.html" %}
    {% block custom_bottom_script %}
    {% endblock custom_bottom_script %}
{% endblock %}