td/api/urls.py
from django.conf.urls import url

from .views import (
    celerybeat_healthz,
    lang_assignment_changed_json,
    lang_assignment_json,
    QuestionnaireView,
    templanguages_json
)


urlpatterns = [
    url(r"^questionnaire/$", QuestionnaireView.as_view(), name="questionnaire"),
    url(r"^templanguages/$", templanguages_json, name="templanguages"),
    url(r"^templanguages/assignment/$", lang_assignment_json, name="templanguages_assignment"),
    url(r"^templanguages/assignment/changed/$", lang_assignment_changed_json, name="templanguages_changed"),
    url(r"^celerybeat/healthz/$", celerybeat_healthz),
]

td/commenting/urls.py
from django.conf.urls import url

from .views import PostCommentView, DeleteCommentView


urlpatterns = [
    url(r"^post/$", PostCommentView.as_view(), name="post_comment"),
    url(r"^delete/(?P<id>\d+)/$", DeleteCommentView.as_view(), name="delete_comment"),
]

td/resources/urls.py
from django.conf.urls import url

from .views import (
    PublisherListView,
    PublisherDetailView,
    PublisherEditView,
    PublisherCreateView,
    TitleListView,
    TitleDetailView,
    TitleEditView,
    TitleCreateView,
    TempLanguageQuestionnaireView,
)

urlpatterns = [
    url(r"publishers/$", PublisherListView.as_view(), name="publisher_list"),
    url(r"publishers/create/$", PublisherCreateView.as_view(), name="publisher_create"),
    url(r"publishers/(?P<pk>\d+)/$", PublisherDetailView.as_view(), name="publisher_detail"),
    url(r"publishers/(?P<pk>\d+)/edit/$", PublisherEditView.as_view(), name="publisher_edit"),
    url(r"titles/$", TitleListView.as_view(), name="title_list"),
    url(r"titles/create/$", TitleCreateView.as_view(), name="title_create"),
    url(r"titles/(?P<slug>[-\w\d]+)/$", TitleDetailView.as_view(), name="title_detail"),
    url(r"titles/(?P<slug>[-\w\d]+)/edit/$", TitleEditView.as_view(), name="title_edit"),

    url(r"^questionnaire/(?P<temp_language>\d+)/$", TempLanguageQuestionnaireView.as_view(), name="templanguage_questionnaire"),
]

td/urls.py
from django.conf import settings
from django.conf.urls import include, url
from django.conf.urls.static import static

from django.contrib import admin

from .views import (
    HomeView,
    AdditionalLanguageListView,
    EthnologueCountryCodeListView,
    EthnologueLanguageCodeListView,
    EthnologueLanguageIndexListView,
    SIL_ISO_639_3ListView,
    WikipediaISOLanguageListView,
    IMBPeopleGroupListView,
    AjaxAdditionalLanguageListView,
    AjaxEthnologueCountryCodeListView,
    AjaxEthnologueLanguageCodeListView,
    AjaxEthnologueLanguageIndexListView,
    AjaxSIL_ISO_639_3ListView,
    AjaxWikipediaISOLanguageListView,
    AjaxIMBPeopleGroupListView,
    codes_text_export,
    names_text_export,
    names_json_export,
    names_json_export_short,
    export_svg,
    languages_autocomplete,
    gateway_languages_autocomplete,
)

urlpatterns = [
    url(r"^$", HomeView.as_view(), name="home"),
    url(r"^siteadmin/", include(admin.site.urls)),
    url(r"^account/", include("account.urls")),
    url(r"^invites/", include("pinax.invitations.urls")),

    url(r"^exports/codes-d43.txt$", codes_text_export, name="codes_text_export"),
    url(r"^exports/langnames.txt$", names_text_export, name="names_text_export"),
    url(r"^exports/langnames.json$", names_json_export, name="names_json_export"),
    url(r"^exports/langnames_short.json$", names_json_export_short, name="names_json_export_short"),
    url(r"^exports/gatewaylanguages-map/$", export_svg, name="gateway_languages_map_export"),

    url(r"^uw/", include("td.resources.urls")),
    url(r"^uw/", include("td.urls_languages")),

    url(r"^publishing/", include("td.publishing.urls")),
    url(r"^api/", include("td.urls_api")),
    url(r"^api/", include("td.api.urls", namespace="api")),
    url(r"^comment/", include("td.commenting.urls", namespace="comment")),
    url(r"^comments/", include("django_comments.urls")),

    url(r"^data-sources/additional-languages/$", AdditionalLanguageListView.as_view(), name="ds_additional_languages"),
    url(r"^data-sources/ethnologue/country-codes/$", EthnologueCountryCodeListView.as_view(), name="ds_ethnologue_country_codes"),
    url(r"^data-sources/ethnologue/language-codes/$", EthnologueLanguageCodeListView.as_view(), name="ds_ethnologue_language_codes"),
    url(r"^data-sources/ethnologue/language-index/$", EthnologueLanguageIndexListView.as_view(), name="ds_ethnologue_language_index"),
    url(r"^data-sources/sil-iso-639-3/$", SIL_ISO_639_3ListView.as_view(), name="ds_sil"),
    url(r"^data-sources/wikipedia/$", WikipediaISOLanguageListView.as_view(), name="ds_wikipedia"),
    url(r"^data-sources/imb/peoplegroups/$", IMBPeopleGroupListView.as_view(), name="ds_imb_peoplegroups"),

    url(r"^ajax/data-sources/additional-languages/$", AjaxAdditionalLanguageListView.as_view(), name="ajax_ds_additional_languages"),
    url(r"^ajax/data-sources/ethnologue/country-codes/$", AjaxEthnologueCountryCodeListView.as_view(), name="ajax_ds_ethnologue_country_codes"),
    url(r"^ajax/data-sources/ethnologue/language-codes/$", AjaxEthnologueLanguageCodeListView.as_view(), name="ajax_ds_ethnologue_language_codes"),
    url(r"^ajax/data-sources/ethnologue/language-index/$", AjaxEthnologueLanguageIndexListView.as_view(), name="ajax_ds_ethnologue_language_index"),
    url(r"^ajax/data-sources/sil-iso-639-3/$", AjaxSIL_ISO_639_3ListView.as_view(), name="ajax_ds_sil"),
    url(r"^ajax/data-sources/wikipedia/$", AjaxWikipediaISOLanguageListView.as_view(), name="ajax_ds_wikipedia"),
    url(r"^ajax/data-sources/imb/peoplegroups/$", AjaxIMBPeopleGroupListView.as_view(), name="ajax_ds_imb_peoplegroups"),

    url(r"^ac/langnames/", languages_autocomplete, name="names_autocomplete"),
    url(r"^ac/gateway-langnames/", gateway_languages_autocomplete, name="gateway_languages")
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

td/publishing/models.py
import base64
from django.conf import settings
from django.db import models
from django.utils import timezone
from django.utils.encoding import python_2_unicode_compatible

from jsonfield import JSONField
from reversion import revisions as reversion

from td.models import Language
from td.publishing.resources import RESOURCE_TYPES


class Organization(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of Organization")
    email = models.CharField(max_length=255, blank=True, verbose_name="Email address")
    phone = models.CharField(max_length=255, blank=True, verbose_name="Phone number")
    website = models.CharField(max_length=255, blank=True)
    location = models.CharField(max_length=255, blank=True)
    languages = models.ManyToManyField(Language, related_name="organizations")
    other = models.TextField(blank=True, verbose_name="Other information")
    checking_entity = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class Contact(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of contact")
    email = models.CharField(max_length=255, blank=True, verbose_name="Email address")
    d43username = models.CharField(max_length=255, blank=True, verbose_name="Door43 username")
    location = models.CharField(max_length=255, blank=True)
    phone = models.CharField(max_length=255, blank=True, verbose_name="Phone number")
    languages = models.ManyToManyField(Language, related_name="contacts")
    org = models.ManyToManyField(Organization, blank=True, verbose_name="organizations")
    other = models.TextField(blank=True, verbose_name="Other information")

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class ConnectionType(models.Model):
    name = models.CharField(max_length=255, verbose_name="Name of Connection Type")
    mutual = models.BooleanField(default=False)

    class Meta:
        ordering = ["name"]

    def __unicode__(self):
        return self.name


class Connection(models.Model):
    con_src = models.ForeignKey(Contact, related_name="source_connections")
    con_dst = models.ForeignKey(Contact, related_name="destination_connections", verbose_name="Connection")
    con_type = models.ForeignKey(ConnectionType, verbose_name="Type")

    class Meta:
        ordering = ["con_src"]

    def __unicode__(self):
        return self.con_src.name


class RecentCommunication(models.Model):
    contact = models.ForeignKey(Contact, related_name="recent_communications")
    communication = models.TextField(blank=True, verbose_name="Message")
    created = models.DateTimeField(auto_now_add=True)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    class Meta:
        ordering = ["contact", "created"]

    def __unicode__(self):
        return self.contact.name


CHECKING_LEVEL_CHOICES = [
    (1, "1"),
    (2, "2"),
    (3, "3"),
]


@python_2_unicode_compatible
class OfficialResourceType(models.Model):
    short_name = models.CharField(max_length=5, help_text="a 5 character identification code")
    long_name = models.CharField(max_length=50, help_text="a more descriptive name")
    description = models.TextField(blank=True)

    def ingest(self, language, publish_request):
        ResourceIngestor = RESOURCE_TYPES.get(self.short_name)
        if ResourceIngestor:
            resource_ingestor = ResourceIngestor(language.code, publish_request)
            chapters = resource_ingestor.fetch_chapters()
            resource_doc = ResourceDocument()
            resource_doc.json_data = chapters
            resource_doc.publish_request = publish_request
            resource_doc.resource_type = publish_request.resource_type
            resource_doc.language = language
            resource_doc.save()

    @property
    def data(self):
        return [
            resource.data
            for resource in self.officialresource_set.order_by("language__code")
        ]

    def __str__(self):
        return "({0}) {1}".format(self.short_name, self.long_name)


@reversion.register()
class OfficialResource(models.Model):
    language = models.ForeignKey(Language, related_name="official_resources", verbose_name="Language")
    resource_type = models.ForeignKey(OfficialResourceType, verbose_name="Official resource type")
    contact = models.ForeignKey(Contact, related_name="official_resources", null=True, blank=True)
    date_started = models.DateField()
    notes = models.TextField(blank=True)
    offline = models.BooleanField(default=False)
    created = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)

    # Publishing
    publish_date = models.DateField(null=True, blank=True)
    version = models.CharField(max_length=10, blank=True)
    source_text = models.ForeignKey(Language, null=True, blank=True, related_name="+")
    source_version = models.CharField(max_length=10, blank=True)
    checking_entity = models.ManyToManyField(Organization, related_name="resource_publications", blank=True)
    contributors = models.ManyToManyField(Contact, related_name="+", blank=True)
    checking_level = models.IntegerField(choices=CHECKING_LEVEL_CHOICES, null=True, blank=True)

    def ingest(self, publish_request):
        self.resource_type.ingest(self.language, publish_request)

    @property
    def data(self):
        """
        {
            "date_modified": "20150826",
            "direction": "ltr",
            "language": "en",
            "status": {
                "checking_entity": "Distant Shores Media; Wycliffe Associates",
                "checking_level": "3",
                "comments": "Original source text.",
                "contributors": "Distant Shores Media",
                "publish_date": "2015-08-26",
                "source_text": "en",
                "source_text_version": "4",
                "version": "4"
            },
            "string": "English"
        }
        """
        return {
            "date_modified": self.created,
            "direction": self.language.get_direction_display(),
            "language": self.language.code,
            "string": self.language.name,
            "status": {
                "checking_entity": self.checking_entity.name if self.checking_entity else "",
                "checking_level": self.checking_level,
                "comments": "\n\n".join([
                    comment.comment
                    for comment in self.comments.order_by("created_at")
                ]),
                "contributors": ", ".join([
                    contact.name
                    for contact in self.contributors.order_by("name")
                ]),
                "publish_date": self.publish_date.strftime("%Y-%m-%d") if self.publish_date else "",
                "source_text": self.source_text.code if self.source_text else "",
                "source_text_version": self.source_version,
                "version": self.version
            }
        }

    def versions(self):
        return reversion.get_for_object(self)

    class Meta:
        ordering = ["language", "contact"]

    def __unicode__(self):
        return "({code}) {resource_type} {version}".format(
            code=self.language.code,
            resource_type=self.resource_type.long_name,
            version=self.version
        )


class Comment(models.Model):
    official_resource = models.ForeignKey(OfficialResource, related_name="comments", null=True)
    comment = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)
    created_by = models.ForeignKey(settings.AUTH_USER_MODEL)


@python_2_unicode_compatible
class PublishRequest(models.Model):
    requestor = models.CharField(max_length=100, verbose_name="Requester name")
    resource_type = models.ForeignKey(OfficialResourceType, null=True, verbose_name='Official resource type')
    language = models.ForeignKey(Language, related_name="publish_requests")
    checking_level = models.IntegerField(choices=CHECKING_LEVEL_CHOICES, verbose_name="Requested checking level")
    source_text = models.ForeignKey(Language, related_name="source_publish_requests", null=True)
    source_version = models.CharField(max_length=10, blank=True)
    contributors = models.TextField(blank=True, help_text="Names or Pseudonyms")
    created_at = models.DateTimeField(default=timezone.now)
    approved_at = models.DateTimeField(default=None, blank=True, null=True, db_index=True)
    requestor_email = models.EmailField(blank=True,
                                        default="",
                                        verbose_name="Requester email",
                                        help_text="email address to be notified of request status")
    license_title = models.TextField(default="CC BY-SA 4.0", blank=True, null=False)
    rejected_at = models.DateTimeField(default=None, null=True, blank=True, verbose_name="Rejected at")
    rejected_by = models.ForeignKey(settings.AUTH_USER_MODEL, default=None, null=True, blank=True,
                                    verbose_name="Rejected by")

    @property
    def permalink(self):
        if self.pk is None:
            return None

        return base64.urlsafe_b64encode(unicode(self.pk).zfill(6))

    @property
    def version(self):
        parts = self.source_version.split(".")
        if len(parts) == 3:
            return ".".join([parts[0], str(int(parts[1]) + 1), parts[2]])
        else:
            return "invalid"

    @property
    def data(self):
        return {
            "mod": self.created_at.strftime("%s"),
            "direction": self.language.get_direction_display(),
            "lc": self.language.code,
            "name": self.language.name,
            "status": {
                "checking_entity": "",  # orgs aren't being added to resources
                "checking_level": self.checking_level,

td/commenting/forms.py
import re

from django_comments.forms import CommentForm

from td.commenting.models import CommentTag


class CommentFormWithTags(CommentForm):

    def __init__(self, *args, **kwargs):
        super(CommentFormWithTags, self).__init__(*args, **kwargs)
        comment_textarea = self.fields["comment"].widget
        comment_textarea.attrs["rows"] = "3"
        comment_textarea.attrs["placeholder"] = "Type a comment here..."

    def process_tags(self):
        comment = self.cleaned_data.get("comment")
        tags = [part.replace("#", "") for part in comment.split() if "#" in part]
        valid_tags = []

        for tag in tags:
            tag = re.sub(r"[\s.,\?\!\;\:\'\"\(\)]*", "", tag)
            try:
                tag_object = CommentTag.objects.get(slug=tag)
                tag_in_comment = r"#" + tag + "(?=[\s.,\?\!\;\:\'\"\(\)]|$)"
                comment = re.sub(r"%s" % tag_in_comment, tag_object.html, comment)
                tag not in valid_tags and valid_tags.append(tag)
            except CommentTag.DoesNotExist:
                # If tag is invalid, don't pick it up
                pass

        return comment, valid_tags

td/templates/publishing/_oresource_row_data.html
<td>
    {% if not version %}
        <a href="{% url "oresource_update" oresource.pk %}" class="btn btn-xs btn-default">
            <i class="fa fa-pencil"></i>
            Edit
        </a>
    {% endif %}
</td>
<td class="language">
    {% if not version %}
        <a href="{% url "oresource_detail" oresource.pk %}">
            {{ oresource.resource_type.long_name }}
        </a>
        <br />
        <strong>{{ oresource.language.name }}</strong>
        <code>{{ oresource.language.code }}</code>
        <br />
    {% endif %}
    <small class="text-muted">
        {% if version %}{{ version.revision.date_created }} / {{ version.revision.user }}{% else %}{{ oresource.created }} / {{ oresource.created_by }}{% endif %}
    </small>
</td>
<td>{{ oresource.contqct }}</td>
<td>{{ oresource.date_started }}</td>
<td>{{ oresource.notes }}</td>
<td>{% if oresource.offline %}<i class="fa fa-fw fa-check"></i>{% endif %}</td>
<td>{{ oresource.publish_date|default:"" }}</td>
<td>{{ oresource.version|default:"" }}</td>
<td>
    {% if oresource.source_text %}{{ oresource.source_text }}{% endif %}
    {% if oresource.source_version %} v{{ oresource.source_version }}{% endif %}
</td>
<td>{% for c in oresource.checking_entity.all %}{{ c.name }}{% if not forloop.last %}, {% endif %}{% endfor %}</td>
<td>{{ oresource.checking_level|default:"" }}</td>

td/templates/publishing/_pr_row_data.html
<td>
    <a href="{% url "publish_request_update" pr.pk %}" class="btn btn-xs btn-primary">Review</a>
</td>
<td>
    {{ pr.requestor }}
</td>
<td>
    {{ pr.resource_type }}
</td>
<td>
    {{ pr.language }}
</td>
<td>
    {{ pr.checking_level }}
</td>
<td>
    {{ pr.contributors }}
</td>
<td>
    {{ pr.created_at }}
</td>

td/templates/publishing/_rejected_row_data.html
<td>
    <a href="{% url "publish_request_update" pr.pk %}" class="btn btn-xs btn-primary">Review</a>
</td>
<td>
    {{ pr.requestor }}
</td>
<td>
    {{ pr.resource_type }}
</td>
<td>
    {{ pr.language }}
</td>
<td>
    {{ pr.contributors }}
</td>
<td>
    {{ pr.rejected_at|date:"M j, Y, g:i A e" }}
</td>

td/templates/publishing/homepage.html
{% extends "site_base.html" %}

{% load i18n %}

{% block head_title %}Home{% endblock %}

{% block body_class %}home{% endblock %}

{% block body_base %}
    <section class="jumbotron">
        <div class="container">
            {% include "_messages.html" %}
            <h1>{% blocktrans %}uW Admin{% endblocktrans %}</h1>
            {% if user.is_authenticated %}
            <p>
                {% blocktrans %}
                What do you want to do?
                {% endblocktrans %}
            </p>
            {% url "contact_list" as contacts_url %}
            {% url "oresource_list" as oresource_list %}
            {% url "oresource_create" as oresource_create %}
            {% blocktrans %}
                <a href="{{ contacts_url }}" class="btn btn-primary large">Contacts</a>
                <a href="{{ oresource_list }}" class="btn btn-primary large">View Resource Records</a>
                <a href="{{ oresource_create }}" class="btn btn-primary large">Create Resource Records</a>
            {% endblocktrans %}
            {% else %}
            <p>
                {% url "account_login" as login_url %}
                {% blocktrans %}
                    Login to get started.
                    <a href="{{ login_url }}" class="btn btn-default">Log In</a>
                {% endblocktrans %}
            </p>
            {% endif %}
        </div>
    </section>
{% endblock %}

td/templates/publishing/openbiblestory_detail.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{{ openbiblestory.language.langname }} Open Bible Story{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
        <li><a href="{% url "obs_list" %}">{% trans "Open Bible Stories" %}</a></li>
        <li>{{ openbiblestory.language.langname }}</li>
    </ul>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        {{ openbiblestory.language.langname }}
                    </h2>
                </div>
                <div class="panel-body">
                    @@@
                </div>
            </div>
        </div>
    </div>
{% endblock %}

td/templates/publishing/openbiblestory_form.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{% if lang %}Update{% else %}Create{% endif %} Open Bible Story{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
        <li><a href="{% url "obs_list" %}">{% trans "Open Bible Stories" %}</a></li>
        <li>{% if lang %}Update{% else %}Create{% endif %} Open Bible Story</li>
    </ul>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        {% if lang %}Update{% else %}Create{% endif %} Open Bible Story{% if lang %} for {{ lang.langname }}{% endif %}
                    </h2>
                </div>
                <div class="panel-body">
                    <form action="" method="post" class="form">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        <button type="submit" class="btn btn-primary pull-right">
                            {% if lang %}Update{% else %}Create{% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block extra_script %}
    <script>
    $(function() {

        $('#id_publish').click(function() {
            var disable = !this.checked;
            $('#id_checking_level').attr('disabled', disable);
            $('#id_checking_entity').attr('disabled', disable);
            $('#id_version').attr('disabled', disable);
        });
    });
    </script>
{% endblock %}

td/templates/publishing/openbiblestory_list.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{% trans "Open Bible Stories" %}{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
        <li>{% trans "Open Bible Stories" %}</li>
    </ul>

    <div class="panel panel-default">
        <div class="panel-heading panel-heading-with-table">
            <h2 class="panel-title">{% trans "Publish Requests" %}</h2>
        </div>
        {% if publish_requests %}
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th></th>
                        <th>Requestor</th>
                        <th>Resource</th>
                        <th>Language</th>
                        <th>Checking Level</th>
                        <th>Contributors</th>
                        <th>Created at</th>
                    </tr>
                </thead>
                <tbody>
                    {% for pr in publish_requests %}
                        <tr>
                            {% include "uwadmin/_pr_row_data.html" with pr=pr %}
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="panel-body">None</div>
        {% endif %}
        <div class="panel-heading panel-heading-with-table">
            <a href="{% url "obs_create" %}" class="btn btn-xs btn-primary pull-right">
                <i class="fa fa-plus"></i>
                Add
            </a>
            <h2 class="panel-title">{% trans "Open Bible Stories" %}</h2>
        </div>
        {% if object_list %}
            <table class="table table-condensed">
                <thead>
                    <tr>
                        <th></th>
                        <th>Language</th>
                        <th>Contact</th>
                        <th>Date Started</th>
                        <th>Notes</th>
                        <th>Offline</th>
                        <th>Publish Date</th>
                        <th>Version</th>
                        <th>Source</th>
                        <th>Checking Entity</th>
                        <th>Checking Level</th>
                    </tr>
                </thead>
                <tbody>
                    {% for obs in object_list %}
                        <tr>
                            {% include "uwadmin/_obs_row_data.html" %}
                        </tr>
                        {% for version in obs.versions %}
                            <tr class="version">
                                {% include "uwadmin/_obs_row_data.html" with obs=version.object_version.object %}
                            </tr>
                        {% endfor %}
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <div class="panel-body">None, <a href="{% url "obs_create" %}">add one</a>!</div>
        {% endif %}
    </div>

{% endblock %}

td/templates/publishing/oresource_detail.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{{ officialresource.language }} Official Resource {{ officialresource.resource_type }}{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
        <li><a href="{% url "oresource_list" %}">{% trans "Official Resources" %}</a></li>
        <li>{{ officialresource.language }}</li>
    </ul>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        {{ officialresource.language }}
                    </h2>
                </div>
                <div class="panel-body">
                    {{ officialresource.resource_type }}
                </div>
            </div>
        </div>
    </div>
{% endblock %}

td/templates/publishing/oresource_form.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}{% if form.language %}Update{% else %}Create{% endif %} Official Resource{% endblock %}

{% block body %}
    <ul class="breadcrumb">
        <li><a href="{% url "home" %}">{% trans "Home" %}</a></li>
        <li><a href="{% url "oresource_list" %}">{% trans "Official Resources" %}</a></li>
        <li>{% if form.language %}Update{% else %}Create{% endif %} Official Resource</li>
    </ul>

    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        {% if form.language %} Update {% else %} Create {% endif %}
                        Official Resource
                    </h2>
                </div>
                <div class="panel-body">
                    <form action="" method="post" class="form">
                        {% csrf_token %}
                        {{ form|bootstrap }}
                        <button type="submit" class="btn btn-primary pull-right">
                            {% if form.language %} Update {% else %} Create {% endif %}
                        </button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}


{% block custom_bottom_script %}
    <script>
    $(function(){
        $("#id_publish").change(function(){
            var disable = !this.checked;
            $('#id_checking_level').attr('disabled', disable);
            $('#id_checking_entity').attr('disabled', disable);
            $('#id_version').attr('disabled', disable);
        });
    });
    </script>
{% endblock %}

td/templates/publishing/publishrequest_confirm_delete.html
{% extends "site_base.html" %}

{% load i18n %}
{% load bootstrap %}

{% block head_title %}Request Publication{% endblock %}

{% block body %}
    <div class="row">
        <div class="col-md-6">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h2 class="panel-title">
                        Reject a Request a Publication
                    </h2>
                </div>
                <div class="panel-body">
                    <form action="" method="post" class="form" enctype="multipart/form-data">
                        {% csrf_token %}
                        <p>Are you sure you want to Reject this request for publication: ({{ object.pk }}) {{ object.resource_type }} in ({{ object.language.code }}) {{ object.language.name }}</p>
                        <div class="actions pull-right">
                            <button type="submit" class="btn btn-primary">Confirm</button>
                            <a href="{% url "publish_request_update" object.pk %}" class="btn btn-danger">Cancel</a>
                        </div>

                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}